name: fastreader
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - bs4
    - langchain
    - langgraph
    - langchain_ollama
    - langchain_openai
    - langchain_community
    - ruff
    - youtube_transcript_api
